export function renderGuardianConsoleHtml(apiToken: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#0b0c09">
  <title>Hallow Guardian</title>
  <style>
    :root{--ink:#11110f;--paper:#d8c9aa;--night:#0b0c09;--panel:#121410;--line:#34362f;--muted:#96998d;--green:#92f5a4;--cyan:#83e5ed;--amber:#efd47e;--red:#f58b8b}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--night);color:#f4f0e5;font-family:Inter,Arial,sans-serif;min-height:100vh}.mono{font-family:"Cascadia Mono",Consolas,monospace}.shell{min-height:100vh;background:radial-gradient(circle at 78% 0,rgba(131,229,237,.08),transparent 27%),linear-gradient(120deg,#080906,#11120e)}
    header{height:78px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 34px;position:sticky;top:0;background:rgba(11,12,9,.92);backdrop-filter:blur(18px);z-index:10}.brand{font:800 15px/1 "Cascadia Mono",monospace;letter-spacing:.24em}.brand em{font-style:normal;color:var(--green)}.status{display:flex;align-items:center;gap:9px;font:12px "Cascadia Mono",monospace;color:var(--muted)}.status i{width:8px;height:8px;border-radius:50%;background:var(--amber);box-shadow:0 0 20px currentColor}.status.online i{background:var(--green)}header nav{justify-self:end;display:flex;gap:24px}header a{color:#ddd9ce;text-decoration:none;font:12px "Cascadia Mono",monospace;text-transform:uppercase;letter-spacing:.08em}
    main{width:min(1380px,calc(100% - 48px));margin:auto;padding:64px 0 100px}.hero{display:grid;grid-template-columns:1.4fr .6fr;gap:50px;align-items:end;margin-bottom:54px}.eyebrow{font:12px "Cascadia Mono",monospace;letter-spacing:.16em;color:var(--cyan);text-transform:uppercase}.hero h1{font:400 clamp(58px,8vw,118px)/.86 Georgia,serif;letter-spacing:-.065em;margin:18px 0 0}.hero h1 em{font-weight:400}.promise{border-left:1px solid var(--line);padding:10px 0 8px 28px;color:#c7c6bc;font-size:16px;line-height:1.55}.promise strong{display:block;color:var(--green);font:13px "Cascadia Mono",monospace;letter-spacing:.1em;margin-bottom:12px}
    .limits{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line);margin-bottom:26px}.limit{padding:20px 22px;border-right:1px solid var(--line)}.limit:last-child{border:0}.limit span{display:block;color:var(--muted);font:10px "Cascadia Mono",monospace;text-transform:uppercase;letter-spacing:.12em;margin-bottom:9px}.limit strong{font:500 17px "Cascadia Mono",monospace}
    .workspace{display:grid;grid-template-columns:410px 1fr;border:1px solid var(--line);min-height:650px;background:rgba(255,255,255,.012)}.controls{padding:30px;border-right:1px solid var(--line)}.stage{padding:30px;min-width:0}.section-label{display:flex;justify-content:space-between;align-items:center;font:11px "Cascadia Mono",monospace;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin-bottom:24px}.section-label b{color:#e8e5da}.field{margin-bottom:18px}.field label{display:block;font:11px "Cascadia Mono",monospace;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);margin-bottom:8px}.field input,.field select{width:100%;border:1px solid var(--line);background:#0b0c09;color:#f2efe5;padding:14px 14px;font:13px "Cascadia Mono",monospace;outline:none}.field input:focus,.field select:focus{border-color:var(--cyan)}.pair{display:grid;grid-template-columns:1fr 1fr;gap:12px}.button{width:100%;border:0;background:var(--paper);color:var(--ink);padding:16px 18px;font:800 12px "Cascadia Mono",monospace;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;transition:.2s}.button:hover{background:#f1e4c8}.button.secondary{background:transparent;color:#f2efe5;border:1px solid var(--line)}.button:disabled{opacity:.35;cursor:not-allowed}.notice{margin-top:22px;padding-top:18px;border-top:1px solid var(--line);color:var(--muted);font:11px/1.7 "Cascadia Mono",monospace}.notice b{color:var(--green)}
    .empty{height:100%;min-height:560px;display:grid;place-items:center;text-align:center;color:var(--muted)}.empty-mark{width:108px;height:108px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;margin:0 auto 24px;position:relative}.empty-mark:after{content:"";position:absolute;width:6px;height:6px;border-radius:50%;background:var(--cyan);box-shadow:0 0 24px var(--cyan)}.empty h2{font:400 36px Georgia,serif;color:#f3efe4;margin:0 0 12px}.empty p{max-width:430px;line-height:1.6;margin:0}
    .passport{display:none}.passport.visible{display:block}.passport-head{display:grid;grid-template-columns:1fr auto;gap:20px;padding-bottom:26px;border-bottom:1px solid var(--line)}.passport h2{font:400 48px Georgia,serif;margin:8px 0 0}.risk{align-self:start;padding:10px 13px;border:1px solid var(--line);font:11px "Cascadia Mono",monospace;text-transform:uppercase}.risk.low-signals{color:var(--green);border-color:rgba(146,245,164,.45)}.risk.elevated{color:var(--amber)}.risk.high,.risk.critical{color:var(--red)}.summary{font:18px/1.55 Georgia,serif;color:#e4e0d5;padding:24px 0;margin:0;border-bottom:1px solid var(--line)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--line)}.metric{padding:20px 18px 20px 0}.metric span{display:block;font:10px "Cascadia Mono",monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.1em;margin-bottom:8px}.metric strong{font:14px "Cascadia Mono",monospace}.signals{padding-top:25px}.signal{display:grid;grid-template-columns:92px 1fr;gap:18px;padding:14px 0;border-top:1px solid #262821}.signal b{font:10px "Cascadia Mono",monospace;color:var(--amber)}.signal strong{font-size:14px}.signal p{margin:5px 0 0;color:var(--muted);font-size:13px;line-height:1.5}.plan{display:none;margin-top:28px;border:1px solid var(--line);border-left:3px solid var(--amber);padding:22px}.plan.visible{display:block}.plan-head{display:flex;justify-content:space-between;gap:20px;margin-bottom:17px}.plan h3{font:700 13px "Cascadia Mono",monospace;letter-spacing:.08em;margin:0}.plan-state{font:11px "Cascadia Mono",monospace;color:var(--amber)}.check{display:grid;grid-template-columns:74px 1fr;gap:14px;padding:10px 0;border-top:1px solid #292b25;font-size:12px;line-height:1.45}.check b{font:10px "Cascadia Mono",monospace}.check.pass b{color:var(--green)}.check.block b{color:var(--red)}.check.approval b{color:var(--amber)}.approval{margin-top:18px;background:rgba(239,212,126,.08);padding:15px;color:#e8ddb8;font:12px/1.5 "Cascadia Mono",monospace}.error{display:none;margin-top:18px;color:var(--red);font:12px/1.5 "Cascadia Mono",monospace}.error.visible{display:block}.loading .button{opacity:.55;pointer-events:none}
    footer{display:flex;justify-content:space-between;border-top:1px solid var(--line);padding:24px 0;margin-top:34px;color:var(--muted);font:10px "Cascadia Mono",monospace;letter-spacing:.1em;text-transform:uppercase}
    @media(max-width:900px){header{grid-template-columns:1fr auto}.status{display:none}.hero{grid-template-columns:1fr}.limits{grid-template-columns:1fr 1fr}.limit{border-bottom:1px solid var(--line)}.workspace{grid-template-columns:1fr}.controls{border-right:0;border-bottom:1px solid var(--line)}.metrics{grid-template-columns:1fr 1fr}main{width:min(100% - 24px,1380px);padding-top:38px}.hero h1{font-size:62px}}
  </style>
</head>
<body><div class="shell">
  <header><div class="brand">HALLOW <em>/ GUARDIAN</em></div><div class="status" id="chain-status"><i></i><span>Checking Robinhood Chain</span></div><nav><a href="/desktop">Workspace</a><a href="/docs">Docs</a></nav></header>
  <main>
    <section class="hero"><div><div class="eyebrow">Proof before action / 001</div><h1>Your agent can act.<br><em>It cannot break your rules.</em></h1></div><div class="promise"><strong>NON-CUSTODIAL BY DESIGN</strong>Hallow reads evidence, explains risk, simulates the plan, and waits for your approval. No seed phrase. No surprise transaction.</div></section>
    <section class="limits" id="limits"><div class="limit"><span>Transaction</span><strong>Loading</strong></div><div class="limit"><span>Daily</span><strong>Loading</strong></div><div class="limit"><span>Memecoin</span><strong>Loading</strong></div><div class="limit"><span>Reserve</span><strong>Loading</strong></div><div class="limit"><span>Broadcast</span><strong>Disabled</strong></div></section>
    <section class="workspace" id="workspace">
      <aside class="controls">
        <div class="section-label"><span>01 / Asset</span><b>Inspect first</b></div>
        <div class="field"><label>Contract address</label><input id="address" value="0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168" spellcheck="false"></div>
        <div class="pair"><div class="field"><label>Network</label><select id="network"><option value="mainnet">Robinhood Chain</option><option value="testnet">Testnet</option></select></div><div class="field"><label>Asset type</label><select id="kind"><option value="auto">Detect</option><option value="rwa">RWA</option><option value="meme">Memecoin</option><option value="stablecoin">Stablecoin</option></select></div></div>
        <button class="button" id="inspect">Create asset passport</button>
        <div style="height:32px"></div><div class="section-label"><span>02 / Intent</span><b>Simulate only</b></div>
        <div class="pair"><div class="field"><label>Action</label><select id="action"><option>buy</option><option>sell</option><option>swap</option><option>lend</option><option>withdraw</option></select></div><div class="field"><label>Amount / USD</label><input id="amount" type="number" min="0" value="50"></div></div>
        <div class="pair"><div class="field"><label>Slippage / bps</label><input id="slippage" type="number" min="0" value="50"></div><div class="field"><label>Reserve after / %</label><input id="reserve" type="number" min="0" max="100" value="20"></div></div>
        <button class="button secondary" id="simulate" disabled>Simulate guarded action</button>
        <div class="error" id="error"></div><div class="notice"><b>PRIVATE DATA STAYS OFFCHAIN.</b><br>Only explicit hashes and transaction evidence are designed for public anchoring.</div>
      </aside>
      <div class="stage"><div class="empty" id="empty"><div><div class="empty-mark"></div><h2>Evidence before opinion.</h2><p>Enter a token contract. Hallow will inspect the chain, compare official registries, and explain what it can prove—and what it cannot.</p></div></div><div class="passport" id="passport"><div class="passport-head"><div><div class="eyebrow">Asset Passport</div><h2 id="asset-title">—</h2></div><div class="risk" id="risk">—</div></div><p class="summary" id="summary"></p><div class="metrics" id="metrics"></div><div class="signals" id="signals"></div><div class="plan" id="plan"></div></div></div>
    </section>
    <footer><span>Hallow Guardian / Robinhood Chain</span><span>Observe → Explain → Simulate → Approve → Prove</span></footer>
  </main>
</div><script>
const API_TOKEN=${JSON.stringify(apiToken)};
const state={passport:null};
const q=(id)=>document.getElementById(id);
const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url,options={}){const headers={...(options.headers||{})};if(options.method&&options.method!=="GET"){headers["Content-Type"]="application/json";headers["X-Hallow-Token"]=API_TOKEN}const response=await fetch(url,{...options,headers});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Hallow could not complete this request.");return payload}
function fail(error){q("error").textContent=error instanceof Error?error.message:String(error);q("error").classList.add("visible")}
function busy(value){q("workspace").classList.toggle("loading",value);q("error").classList.remove("visible")}
async function loadStatus(){try{const data=await api("/api/guardian/status");const s=data.status,p=data.policy;q("chain-status").classList.toggle("online",s.connected);q("chain-status").querySelector("span").textContent=s.connected?"Robinhood Chain · block "+Number(s.block_number).toLocaleString():"Chain unavailable";q("limits").innerHTML=[["Transaction","$"+p.max_transaction_usd],["Daily","$"+p.max_daily_usd],["Memecoin",p.max_memecoin_allocation_percent+"% max"],["Reserve",p.min_reserve_percent+"% min"],["Broadcast","Disabled"]].map(x=>'<div class="limit"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>').join("")}catch(error){fail(error)}}
function showPassport(passport){state.passport=passport;q("empty").style.display="none";q("passport").classList.add("visible");q("simulate").disabled=false;q("asset-title").textContent=passport.contract.symbol||passport.stock_token?.symbol||"Unknown asset";q("risk").textContent=passport.risk.band.replace("-"," ")+" · "+passport.risk.score;q("risk").className="risk "+passport.risk.band;q("summary").textContent=passport.summary;q("metrics").innerHTML=[["Type",passport.kind],["Canonical",passport.canonical?"Verified":"Not verified"],["Code",passport.contract.code_bytes.toLocaleString()+" bytes"],["Block",passport.block_number?.toLocaleString()||"—"]].map(x=>'<div class="metric"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>').join("");const signals=passport.risk.signals.length?passport.risk.signals:[{severity:"info",title:"No major signal detected",detail:"This remains a bounded inspection, not a promise of safety."}];q("signals").innerHTML='<div class="section-label"><span>Evidence signals</span><b>'+signals.length+' found</b></div>'+signals.map(s=>'<div class="signal"><b>'+esc(s.severity)+'</b><div><strong>'+esc(s.title)+'</strong><p>'+esc(s.detail)+'</p></div></div>').join("")}
function showPlan(record){const p=record.plan;q("plan").classList.add("visible");q("plan").innerHTML='<div class="plan-head"><h3>GUARDIAN PLAN / '+esc(p.action.toUpperCase())+'</h3><span class="plan-state">'+esc(p.state.replaceAll("_"," ").toUpperCase())+'</span></div>'+p.checks.map(c=>'<div class="check '+esc(c.status)+'"><b>'+esc(c.status.toUpperCase())+'</b><span><strong>'+esc(c.label)+'</strong><br>'+esc(c.detail)+'</span></div>').join("")+'<div class="approval">'+esc(p.human_summary)+(record.approval?'<br><br>Approval created: '+esc(record.approval.id):"")+'</div>';q("plan").scrollIntoView({behavior:"smooth",block:"nearest"})}
q("inspect").addEventListener("click",async()=>{busy(true);try{const params=new URLSearchParams({address:q("address").value,network:q("network").value,kind:q("kind").value});const data=await api("/api/guardian/inspect?"+params);showPassport(data.passport)}catch(error){fail(error)}finally{busy(false)}});
q("simulate").addEventListener("click",async()=>{busy(true);try{const data=await api("/api/guardian/plan",{method:"POST",body:JSON.stringify({address:q("address").value,network:q("network").value,kind:q("kind").value,action:q("action").value,amount_usd:Number(q("amount").value),slippage_bps:Number(q("slippage").value),projected_reserve_percent:Number(q("reserve").value)})});showPlan(data)}catch(error){fail(error)}finally{busy(false)}});
loadStatus();
</script></body></html>`;
}
